### ISSUE TITLE
Can't delete another computers file

### ISSUE THREAD

**Issue by R0sef13ld4ever** [Fs00/Win10BloatRemover#6] opened 2021-10-27 07:33 UTC
<!--
Hi!
Thanks for taking the time to write an issue.

Before starting, if you want to:
- ask a question about the tool
- share an idea of a feature you would like to see implemented

then **open a new discussion** by going to "Discussions" at the top of the page -> "New discussion".
This helps us to keep Issues focused just on bugs and things that need to be improved. Thanks!

Still here? So you want to report a problem you have with the program.
In your description of the problem, don't forget to include these things:
- Windows version
- Program version
- Edition of Windows you are running the program on (Home, Pro, etc.)
- Steps to reproduce the problem (if applicable)

You can delete this introductory text when you are done.
Thank you!

[write your report under the following line]
--!>

**Comment by Fs00** [comment] 2021-11-21 16:46
Closing this due to lack of details.
Feel free to reopen in case you have more information on the issue, such as reproduction steps, the exact system you are using etc.

**Closed by Fs00** 2021-11-21 16:46 UTC
